"""Private local storage for manual transfer evidence."""

from pathlib import Path

from config import PAYMENT_EVIDENCE_ROOT


ROOT = Path(PAYMENT_EVIDENCE_ROOT)


def save(data: bytes, key: str) -> str:
    ROOT.mkdir(parents=True, exist_ok=True)
    path = ROOT / key
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return str(path)


def resolve(key: str) -> Path:
    # Keys are generated by the server and never contain path separators.
    safe = Path(key).name
    path = ROOT / safe
    if path.parent != ROOT:
        raise ValueError("invalid_payment_evidence_key")
    return path


def delete(key: str) -> None:
    try:
        resolve(key).unlink()
    except FileNotFoundError:
        pass
