"""payments and uzs currency

Revision ID: a207cd2314b3
Revises: b9d10da3471c
Create Date: 2026-09-10 07:08:27.540104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a207cd2314b3'
down_revision: Union[str, None] = 'b9d10da3471c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=12), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('merchant_trans_id', sa.String(length=80), nullable=False),
    sa.Column('click_trans_id', sa.String(length=40), nullable=True),
    sa.Column('click_paydoc_id', sa.String(length=40), nullable=True),
    sa.Column('merchant_prepare_id', sa.String(length=40), nullable=True),
    sa.Column('merchant_confirm_id', sa.String(length=40), nullable=True),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('failure_code', sa.String(length=20), nullable=True),
    sa.Column('failure_note', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_payments_idempotency_key')),
    sa.UniqueConstraint('merchant_trans_id', name=op.f('uq_payments_merchant_trans_id'))
    )
    op.create_index(op.f('ix_payments_click_trans_id'), 'payments', ['click_trans_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('payment_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=12), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('click_trans_id', sa.String(length=40), nullable=True),
    sa.Column('provider_error_code', sa.String(length=20), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_payment_events_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events'))
    )
    op.create_index(op.f('ix_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=False)
    # UZS currency migration: existing demo/catalog rows move from IDR to UZS
    op.execute("UPDATE products SET currency = 'UZS' WHERE currency = 'IDR'")
    op.execute("UPDATE orders SET currency = 'UZS' WHERE currency = 'IDR'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_events_payment_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_click_trans_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
